const websites = [
  {name:"Google",url:"https://google.com"},
  {name:"YouTube",url:"https://youtube.com"},
  {name:"ChatGPT",url:"https://chatgpt.com"},
  {name:"Wikipedia",url:"https://wikipedia.org"},
  {name:"Instagram",url:"https://instagram.com"},
  {name:"Facebook",url:"https://facebook.com"},
  {name:"X",url:"https://x.com"},
  {name:"Spotify",url:"https://spotify.com"},
  {name:"Netflix",url:"https://netflix.com"},
  {name:"Amazon",url:"https://amazon.in"},
  {name:"Flipkart",url:"https://flipkart.com"},
  {name:"Gmail",url:"https://mail.google.com"},
  {name:"Google Maps",url:"https://maps.google.com"},
  {name:"Google Drive",url:"https://drive.google.com"},
  {name:"GitHub",url:"https://github.com"},
  {name:"Reddit",url:"https://reddit.com"},
  {name:"Discord",url:"https://discord.com"},
  {name:"LinkedIn",url:"https://linkedin.com"},
  {name:"Pinterest",url:"https://pinterest.com"},
  {name:"Poki Games",url:"https://poki.com"},
  {name:"Cruise Money",url:"https://cruise.money/"},
{name:"GitHub",url:"https://github.com"},
  {name:"Reddit",url:"https://reddit.com"},
  {name:"Discord",url:"https://discord.com"},
  {name:"LinkedIn",url:"https://linkedin.com"},
  {name:"Pinterest",url:"https://pinterest.com"},
  {name:"Poki Games",url:"https://poki.com"},
  {name:"Twitch",url:"https://twitch.tv"},
  {name:"Stack Overflow",url:"https://stackoverflow.com"},
  {name:"Medium",url:"https://medium.com"},
  {name:"Dev.to",url:"https://dev.to"},
  {name:"Figma",url:"https://figma.com"},
  {name:"Slack",url:"https://slack.com"},
  {name:"Trello",url:"https://trello.com"},
  {name:"Notion",url:"https://notion.so"},
  {name:"Canva",url:"https://canva.com"},
  {name:"VS Code",url:"https://vscode.dev"},
  {name:"Vercel",url:"https://vercel.com"},
  {name:"Netlify",url:"https://netlify.com"},
  {name:"Heroku",url:"https://heroku.com"},
  {name:"AWS",url:"https://aws.amazon.com"},
  {name:"Google Classroom",url:"https://classroom.google.com"},
  {name:"Coursera",url:"https://coursera.org"},
  {name:"Udemy",url:"https://udemy.com"},
  {name:"CodePen",url:"https://codepen.io"},
  {name:"JSFiddle",url:"https://jsfiddle.net"},
  {name:"Replit",url:"https://replit.com"},
  {name:"WhatsApp",url:"https://web.whatsapp.com"},
  {name:"Telegram",url:"https://web.telegram.org"},
  {name:"Twitter",url:"https://twitter.com"},
  {name:"Quora",url:"https://quora.com"},
  {name:"Airbnb",url:"https://airbnb.com"},
  {name:"Uber",url:"https://uber.com"},
  {name:"Booking.com",url:"https://booking.com"},
  {name:"eBay",url:"https://ebay.com"},
  {name:"PayPal",url:"https://paypal.com"},
  {name:"Stripe",url:"https://stripe.com"},
  {name:"Adobe Creative Cloud",url:"https://adobe.com"},
  {name:"Microsoft Office 365",url:"https://office.com"},
  {name:"Apple iCloud",url:"https://icloud.com"},
  {name:"Dropbox",url:"https://dropbox.com"},
  {name:"OneDrive",url:"https://onedrive.live.com"},
  {name:"Box",url:"https://box.com"},
  {name:"Zoom",url:"https://zoom.us"},
  {name:"Google Meet",url:"https://meet.google.com"},
  {name:"Skype",url:"https://skype.com"},
  {name:"SoundCloud",url:"https://soundcloud.com"},
  {name:"Bandcamp",url:"https://bandcamp.com"},
  {name:"Tidal",url:"https://tidal.com"},
  {name:"Apple Music",url:"https://music.apple.com"},
  {name:"Amazon Music",url:"https://music.amazon.com"},
  {name:"YouTube Music",url:"https://music.youtube.com"},
  {name:"DuckDuckGo",url:"https://duckduckgo.com"},
  {name:"Bing",url:"https://bing.com"},
  {name:"Yahoo",url:"https://yahoo.com"},
  {name:"Wolfram Alpha",url:"https://wolframalpha.com"},
  {name:"IMDb",url:"https://imdb.com"},
  {name:"Rotten Tomatoes",url:"https://rottentomatoes.com"},
  {name:"Goodreads",url:"https://goodreads.com"},
  {name:"TikTok",url:"https://tiktok.com"},
  {name:"Snapchat",url:"https://snapchat.com"},
  {name:"Signal",url:"https://signal.org"},
  {name:"Proton Mail",url:"https://proton.me"},
  {name:"Etsy",url:"https://etsy.com"},
  {name:"ASOS",url:"https://asos.com"},
  {name:"H&M",url:"https://hm.com"},
  {name:"Zara",url:"https://zara.com"},
  {name:"Target",url:"https://target.com"},
  {name:"Walmart",url:"https://walmart.com"},
  {name:"Best Buy",url:"https://bestbuy.com"},
  {name:"IKEA",url:"https://ikea.com"},
  {name:"DoorDash",url:"https://doordash.com"},
  {name:"Uber Eats",url:"https://ubereats.com"},
  {name:"Grubhub",url:"https://grubhub.com"},
  {name:"Zomato",url:"https://zomato.com"},
  {name:"Swiggy",url:"https://swiggy.com"},
  {name:"Expedia",url:"https://expedia.com"},
  {name:"Kayak",url:"https://kayak.com"},
  {name:"Skyscanner",url:"https://skyscanner.com"},
  {name:"Hotels.com",url:"https://hotels.com"},
  {name:"Blender",url:"https://blender.org"},
  {name:"GIMP",url:"https://gimp.org"},
  {name:"Photopea",url:"https://photopea.com"},
  {name:"Inkscape",url:"https://inkscape.org"},
  {name:"Deezer",url:"https://deezer.com"},
  {name:"Mastodon",url:"https://mastodon.social"},
  {name:"Bluesky",url:"https://bsky.app"},
  {name:"Threads",url:"https://threads.net"},
  {name:"Bitbucket",url:"https://bitbucket.org"},
  {name:"GitLab",url:"https://gitlab.com"},
  {name:"npm",url:"https://npmjs.com"},
  {name:"PyPI",url:"https://pypi.org"},
  {name:"Docker Hub",url:"https://hub.docker.com"},
  {name:"Jira",url:"https://jira.com"},
  {name:"Confluence",url:"https://confluence.com"},
  {name:"Monday.com",url:"https://monday.com"},
  {name:"Asana",url:"https://asana.com"},
  {name:"Todoist",url:"https://todoist.com"},
  {name:"Obsidian",url:"https://obsidian.md"},
  {name:"Evernote",url:"https://evernote.com"},
  {name:"OneNote",url:"https://onenote.com"},
  {name:"Typeform",url:"https://typeform.com"},
  {name:"Jotform",url:"https://jotform.com"},
  {name:"SurveyMonkey",url:"https://surveymonkey.com"},
  {name:"Google Forms",url:"https://forms.google.com"},
  {name:"Mailchimp",url:"https://mailchimp.com"},
  {name:"Substack",url:"https://substack.com"},
  {name:"Beehiiv",url:"https://beehiiv.com"},
  {name:"ConvertKit",url:"https://convertkit.com"},
  {name:"Patreon",url:"https://patreon.com"},
  {name:"Ko-fi",url:"https://ko-fi.com"},
  {name:"Buy Me a Coffee",url:"https://buymeacoffee.com"},
  {name:"Gumroad",url:"https://gumroad.com"},
  {name:"Wise",url:"https://wise.com"},
  {name:"Revolut",url:"https://revolut.com"},
  {name:"Robinhood",url:"https://robinhood.com"},
  {name:"Crypto.com",url:"https://crypto.com"},
  {name:"Coinbase",url:"https://coinbase.com"},
  {name:"Kraken",url:"https://kraken.com"},
  {name:"Binance",url:"https://binance.com"},
  {name:"OKX",url:"https://okx.com"},
  {name:"Bybit",url:"https://bybit.com"},
  {name:"Kucoin",url:"https://kucoin.com"},
  {name:"Bitfinex",url:"https://bitfinex.com"},
  {name:"Gemini",url:"https://gemini.com"},
  {name:"Uniswap",url:"https://uniswap.org"},
  {name:"Aave",url:"https://aave.com"},
  {name:"Curve Finance",url:"https://curve.fi"},
  {name:"Pancakeswap",url:"https://pancakeswap.finance"},
  {name:"OpenSea",url:"https://opensea.io"},
  {name:"Rarible",url:"https://rarible.com"},
  {name:"SuperRare",url:"https://superrare.com"},
  {name:"Audible",url:"https://audible.com"},
  {name:"Kindle",url:"https://read.amazon.com"},
  {name:"Wattpad",url:"https://wattpad.com"},
  {name:"Letterboxd",url:"https://letterboxd.com"},
  {name:"Vibes",url:"https://vibes.co"},
  {name:"Shazam",url:"https://shazam.com"},
  {name:"Genius",url:"https://genius.com"},
  {name:"AZLyrics",url:"https://azlyrics.com"},
  {name:"MusicBrainz",url:"https://musicbrainz.org"},
  {name:"Last.fm",url:"https://last.fm"},
  {name:"Rarbg",url:"https://rarbg.to"},
  {name:"The Pirate Bay",url:"https://thepiratebay.org"},
  {name:"1337x",url:"https://1337x.to"},
  {name:"YTS",url:"https://yts.mx"},
  {name:"Popcorn Time",url:"https://popcorntime.app"},
  {name:"Stremio",url:"https://stremio.com"},
  {name:"Kodi",url:"https://kodi.tv"},
  {name:"Plex",url:"https://plex.tv"},
  {name:"Emby",url:"https://emby.media"},
  {name:"Jellyfin",url:"https://jellyfin.org"},
  {name:"VLC",url:"https://videolan.org"},
  {name:"MPV",url:"https://mpv.io"},
  {name:"MPC-HC",url:"https://mpc-hc.org"},
  {name:"Potplayer",url:"https://potplayer.daum.net"},
  {name:"WinRAR",url:"https://win-rar.com"},
  {name:"7-Zip",url:"https://7-zip.org"},
  {name:"PeaZip",url:"https://peazip.github.io"},
  {name:"Bandizip",url:"https://bandisoft.com"},
  {name:"CCleaner",url:"https://ccleaner.com"},
  {name:"Malwarebytes",url:"https://malwarebytes.com"},
  {name:"Norton",url:"https://norton.com"},
  {name:"McAfee",url:"https://mcafee.com"},
  {name:"Avast",url:"https://avast.com"},
  {name:"Kaspersky",url:"https://kaspersky.com"},
  {name:"Bitdefender",url:"https://bitdefender.com"},
  {name:"Windows Defender",url:"https://microsoft.com/security"},
  {name:"Autoruns",url:"https://docs.microsoft.com/en-us/sysinternals/downloads/autoruns"},
  {name:"Task Manager",url:"https://microsoft.com"},
  {name:"Resource Monitor",url:"https://microsoft.com"},
  {name:"Disk Management",url:"https://microsoft.com"},
  {name:"Device Manager",url:"https://microsoft.com"},
  {name:"Services",url:"https://microsoft.com"},
  {name:"Event Viewer",url:"https://microsoft.com"},
  {name:"System Restore",url:"https://microsoft.com"},
  {name:"Virtual Box",url:"https://virtualbox.org"},
  {name:"VMware",url:"https://vmware.com"},
  {name:"Hyper-V",url:"https://microsoft.com"},
  {name:"QEMU",url:"https://qemu.org"},
  {name:"Proxmox",url:"https://proxmox.com"},
  {name:"Citrix",url:"https://citrix.com"},
  {name:"Parallels",url:"https://parallels.com"},
  {name:"Ubuntu",url:"https://ubuntu.com"},
  {name:"Debian",url:"https://debian.org"},
  {name:"CentOS",url:"https://centos.org"},
  {name:"Fedora",url:"https://fedoraproject.org"},
  {name:"Arch Linux",url:"https://archlinux.org"},
  {name:"Manjaro",url:"https://manjaro.org"},
  {name:"Linux Mint",url:"https://linuxmint.com"},
  {name:"Elementary OS",url:"https://elementary.io"},
  {name:"Pop OS",url:"https://pop.system76.com"},
  {name:"Deepin",url:"https://deepin.org"},
  {name:"Zorin OS",url:"https://zorin.com"},
  {name:"Xubuntu",url:"https://xubuntu.org"},
  {name:"Lubuntu",url:"https://lubuntu.me"},
  {name:"Puppy Linux",url:"https://puppylinux.com"},
  {name:"Alpine Linux",url:"https://alpinelinux.org"},
  {name:"NixOS",url:"https://nixos.org"},
  {name:"Slackware",url:"https://slackware.com"},
  {name:"Gentoo",url:"https://gentoo.org"},
  {name:"OpenBSD",url:"https://openbsd.org"},
  {name:"FreeBSD",url:"https://freebsd.org"},
  {name:"ReactOS",url:"https://reactos.org"},
  {name:"MX Linux",url:"https://mxlinux.org"},
  {name:"AntiX",url:"https://antixlinux.com"},
  {name:"Raspberry Pi OS",url:"https://raspberrypi.org"},
  {name:"Kali Linux",url:"https://kali.org"},
  {name:"Parrot OS",url:"https://parrotsec.org"},
  {name:"Black Arch",url:"https://blackarch.org"},
  {name:"Tails",url:"https://tails.boum.org"},
  {name:"Whonix",url:"https://whonix.org"},
  {name:"Qubes OS",url:"https://qubes-os.org"},
  {name:"node.js",url:"https://nodejs.org"},
  {name:"Python",url:"https://python.org"},
  {name:"Ruby",url:"https://ruby-lang.org"},
  {name:"PHP",url:"https://php.net"},
  {name:"Java",url:"https://java.com"},
  {name:"C#",url:"https://microsoft.com/en-us/dotnet"},
  {name:"Go",url:"https://golang.org"},
  {name:"Rust",url:"https://rust-lang.org"},
  {name:"Kotlin",url:"https://kotlinlang.org"},
  {name:"Swift",url:"https://swift.org"},
  {name:"R",url:"https://r-project.org"},
  {name:"Julia",url:"https://julialang.org"},
  {name:"MATLAB",url:"https://mathworks.com"},
  {name:"Octave",url:"https://gnu.org/software/octave"},
  {name:"Perl",url:"https://perl.org"},
  {name:"Lua",url:"https://lua.org"},
  {name:"Haskell",url:"https://haskell.org"},
  {name:"Clojure",url:"https://clojure.org"},
  {name:"Elixir",url:"https://elixir-lang.org"},
  {name:"Erlang",url:"https://erlang.org"},
  {name:"Scala",url:"https://scala-lang.org"},
  {name:"Groovy",url:"https://groovy-lang.org"},
  {name:"Coffeescript",url:"https://coffeescript.org"},
  {name:"TypeScript",url:"https://typescriptlang.org"},
  {name:"Dart",url:"https://dart.dev"},
  {name:"Flutter",url:"https://flutter.dev"},
  {name:"React Native",url:"https://reactnative.dev"},
  {name:"Vue.js",url:"https://vuejs.org"},
  {name:"Angular",url:"https://angular.io"},
  {name:"Svelte",url:"https://svelte.dev"},
  {name:"Next.js",url:"https://nextjs.org"},
  {name:"Nuxt.js",url:"https://nuxtjs.org"},
  {name:"Astro",url:"https://astro.build"},
  {name:"Remix",url:"https://remix.run"},
  {name:"SvelteKit",url:"https://kit.svelte.dev"},
  {name:"Django",url:"https://djangoproject.com"},
  {name:"Flask",url:"https://flask.palletsprojects.com"},
  {name:"FastAPI",url:"https://fastapi.tiangolo.com"},
  {name:"Pyramid",url:"https://trypyramid.com"},
  {name:"Tornado",url:"https://www.tornadoweb.org"},
  {name:"Bottle",url:"https://bottlepy.org"},
  {name:"Cherry Py",url:"https://cherrypy.dev"},
  {name:"Falcon",url:"https://falconframework.org"},
  {name:"Aiohttp",url:"https://aiohttp.readthedocs.io"},
  {name:"Starlette",url:"https://starlette.io"},
  {name:"Rails",url:"https://rubyonrails.org"},
  {name:"Sinatra",url:"https://sinatrarb.com"},
  {name:"Hanami",url:"https://hanamirb.org"},
  {name:"Spring Boot",url:"https://spring.io/projects/spring-boot"},
  {name:"Play Framework",url:"https://www.playframework.com"},
  {name:"Grails",url:"https://grails.org"},
  {name:"Micronaut",url:"https://micronaut.io"},
  {name:"Quarkus",url:"https://quarkus.io"},
  {name:"Dropwizard",url:"https://www.dropwizard.io"},
  {name:"Vert.x",url:"https://vertx.io"},
  {name:"Akka",url:"https://akka.io"},
  {name:"Play2",url:"https://www.playframework.com"},
  {name:"Lagom",url:"https://www.lagomframework.com"},
  {name:"Finatra",url:"https://twitter.github.io/finatra"},
  {name:"Spark",url:"https://sparkjava.com"},
  {name:"Javalin",url:"https://javalin.io"},
  {name:"Helidon",url:"https://helidon.io"},
  {name:"MicroProfile",url:"https://microprofile.io"},
  {name:"Apache Struts",url:"https://struts.apache.org"},
  {name:"Apache Wicket",url:"https://wicket.apache.org"},
  {name:"Vaadin",url:"https://vaadin.com"},
  {name:"GWT",url:"https://www.gwtproject.org"},
  {name:"JSF",url:"https://javaserverfaces.java.net"},
  {name:"Tapestry",url:"https://tapestry.apache.org"},
  {name:"Seam",url:"https://seamframework.org"},
  {name:"Stripes",url:"https://stripesframework.org"},
  {name:"Echo",url:"https://echo.labstack.com"},
  {name:"Gin Gonic",url:"https://gin-gonic.com"},
  {name:"Beego",url:"https://beego.me"},
  {name:"Revel",url:"https://revel.run"},
  {name:"Buffalo",url:"https://gobuffalo.io"},
  {name:"Chi",url:"https://go-chi.io"},
  {name:"Fiber",url:"https://gofiber.io"},
  {name:"Iris",url:"https://iris-go.com"},
  {name:"Mux",url:"https://github.com/gorilla/mux"},
  {name:"Martini",url:"https://github.com/go-martini/martini"},
  {name:"Goji",url:"https://goji.io"},
  {name:"Httprouter",url:"https://github.com/julienschmidt/httprouter"},
  {name:"Web3.py",url:"https://web3py.readthedocs.io"},
  {name:"Ethers.js",url:"https://docs.ethers.org"},
  {name:"Web3.js",url:"https://web3js.readthedocs.io"},
  {name:"Truffle",url:"https://www.trufflesuite.com"},
  {name:"Hardhat",url:"https://hardhat.org"},
  {name:"Foundry",url:"https://book.getfoundry.sh"},
  {name:"Brownie",url:"https://eth-brownie.readthedocs.io"},
  {name:"Alchemy",url:"https://alchemy.com"},
  {name:"Infura",url:"https://infura.io"},
  {name:"QuickNode",url:"https://quicknode.com"},
  {name:"Ankr",url:"https://ankr.com"},
  {name:"Moralis",url:"https://moralis.io"},
  {name:"Covalent",url:"https://covalenthq.com"},
  {name:"TheGraph",url:"https://thegraph.com"},
  {name:"DeFiPulse",url:"https://defipulse.com"},
  {name:"Zapper",url:"https://zapper.fi"},
  {name:"Zerion",url:"https://zerion.io"},
  {name:"DeBank",url:"https://debank.com"},
  {name:"Etherscan",url:"https://etherscan.io"},
  {name:"Bscscan",url:"https://bscscan.com"},
  {name:"Polygonscan",url:"https://polygonscan.com"},
  {name:"Snowtrace",url:"https://snowtrace.io"},
  {name:"FTMscan",url:"https://ftmscan.com"},
  {name:"Solscan",url:"https://solscan.io"},
  {name:"CronoScan",url:"https://cronoscan.com"},
  {name:"MoonScan",url:"https://moonscan.io"},
  {name:"Routescan",url:"https://routescan.io"},
  {name:"Arbiscan",url:"https://arbiscan.io"},
  {name:"Optimistic Etherscan",url:"https://optimistic.etherscan.io"},
  {name:"Gnosisscan",url:"https://gnosisscan.io"},
  {name:"Scroll Scan",url:"https://scrollscan.com"},
  {name:"Lineascan",url:"https://lineascan.build"},
  {name:"Basescan",url:"https://basescan.org"},
  {name:"Zetascan",url:"https://zetachain.blockscout.com"},
  {name:"ICP Dash",url:"https://dashboard.internetcomputer.org"},
  {name:"Cardanoscan",url:"https://cardanoscan.io"},
  {name:"Adapools",url:"https://adapools.org"},
  {name:"Pool PM",url:"https://pool.pm"},
  {name:"Tonviewer",url:"https://tonviewer.com"},
  {name:"Tonscan",url:"https://tonscan.org"},
  {name:"Aptos Explorer",url:"https://explorer.aptoslabs.com"},
  {name:"Move Scan",url:"https://movescan.io"},
  {name:"Sui Explorer",url:"https://suiexplorer.com"},
  {name:"Sui Scan",url:"https://suiscan.xyz"},
  {name:"Thala Labs",url:"https://app.thala.fi"},
  {name:"Aftermath Finance",url:"https://aftermath.finance"},
  {name:"Econia",url:"https://www.econia.dev"},
  {name:"Orca",url:"https://orca.so"},
  {name:"Raydium",url:"https://raydium.io"},
  {name:"Magic Eden",url:"https://magiceden.io"},
  {name:"Tensor",url:"https://tensor.trade"},
  {name:"Blur",url:"https://blur.io"},
  {name:"X2Y2",url:"https://x2y2.io"},
  {name:"LooksRare",url:"https://looksrare.org"},
  {name:"Sudoswap",url:"https://sudoswap.xyz"},
  {name:"Banksea",url:"https://banksea.io"},
  {name:"Trove",url:"https://trove.treasure.lol"},
  {name:"Dust Labs",url:"https://dust.dev"},
  {name:"NFTFi",url:"https://nftfi.com"},
  {name:"BendDAO",url:"https://benddao.xyz"},
  {name:"Azuki",url:"https://azuki.com"},
  {name:"Clone X",url:"https://clonex.rtfkt.com"},
  {name:"Cool Cats",url:"https://coolcatsnft.com"},
  {name:"Pudgy Penguins",url:"https://pudgypenguins.io"},
  {name:"DeGods",url:"https://degods.com"},
  {name:"Okay Bears",url:"https://okaybearsofficial.com"},
  {name:"Moonbirds",url:"https://moonbirds.xyz"},
  {name:"Doodles",url:"https://doodles.app"},
  {name:"World of Women",url:"https://www.worldofwomen.art"},
  {name:"Art Blocks",url:"https://artblocks.io"},
  {name:"Foundation",url:"https://foundation.app"},
  {name:"Catalog",url:"https://catalog.works"},
  {name:"Mirror",url:"https://mirror.xyz"},
  {name:"Sound",url:"https://sound.xyz"},
  {name:"Zora",url:"https://zora.co"},
  {name:"Highlights",url:"https://highlights.xyz"},
  {name:"1inch",url:"https://1inch.io"},
  {name:"ParaSwap",url:"https://paraswap.io"},
  {name:"Matcha",url:"https://matcha.xyz"},
  {name:"SushiSwap",url:"https://sushi.com"},
  {name:"Balancer",url:"https://balancer.fi"},
  {name:"Bancor",url:"https://bancor.network"},
  {name:"Kyberswap",url:"https://kyberswap.com"},
  {name:"Quickswap",url:"https://quickswap.exchange"},
  {name:"Uniswap V2",url:"https://v2.uniswap.org"},
  {name:"Uniswap V3",url:"https://app.uniswap.org"},
  {name:"Compound",url:"https://compound.finance"},
  {name:"Maker",url:"https://makerdao.com"},
  {name:"Yearn",url:"https://yearn.finance"},
  {name:"Curve",url:"https://curve.fi"},
  {name:"Lido",url:"https://lido.fi"},
  {name:"Rocket Pool",url:"https://rocketpool.net"},
  {name:"Convex",url:"https://convexfinance.com"},
  {name:"Stargate",url:"https://stargate.finance"}
];
const appList = document.getElementById("appList");

websites.forEach(site => {
  const div = document.createElement("div");

  div.className = "app";

  div.innerHTML = `
    <h3>${site.name}</h3>
    <button onclick="window.open('${site.url}','_blank')">
      Open
    </button>
  `;

  appList.appendChild(div);
});
